export interface StyleConcept {
  name: string;
  category: 'Structural' | 'Atmospheric' | 'Organic' | 'Chromatic' | 'Abstract';
}

export const STYLES: StyleConcept[] = [
  { name: "Accretion", category: "Structural" },
  { name: "Amaranthine", category: "Abstract" },
  { name: "Amorphous", category: "Abstract" },
  { name: "Anamorphic", category: "Structural" },
  { name: "Anthracite", category: "Chromatic" },
  { name: "Aural", category: "Atmospheric" },
  { name: "Basaltic", category: "Chromatic" },
  { name: "Cachinnation", category: "Abstract" },
  { name: "Cerulean", category: "Chromatic" },
  { name: "Chiaroscuro", category: "Atmospheric" },
  { name: "Cinnabar", category: "Chromatic" },
  { name: "Coquelicot", category: "Chromatic" },
  { name: "Crepuscular", category: "Atmospheric" },
  { name: "Damask", category: "Chromatic" },
  { name: "Dendritic", category: "Organic" },
  { name: "Diaphanous", category: "Abstract" },
  { name: "Gleaming", category: "Abstract" },
  { name: "Gossamer", category: "Organic" },
  { name: "Halation", category: "Atmospheric" },
  { name: "Imbricated", category: "Structural" },
  { name: "Incarnadine", category: "Chromatic" },
  { name: "Irradiance", category: "Atmospheric" },
  { name: "Labrys", category: "Structural" },
  { name: "Lattice", category: "Structural" },
  { name: "Luminance", category: "Atmospheric" },
  { name: "Mandelbrot", category: "Structural" },
  { name: "Marbled", category: "Organic" },
  { name: "Monopsis", category: "Abstract" },
  { name: "Nebulous", category: "Abstract" },
  { name: "Nephology", category: "Organic" },
  { name: "Noctilucent", category: "Atmospheric" },
  { name: "Umbralis", category: "Atmospheric" },
  { name: "Parhelion", category: "Atmospheric" },
  { name: "Pavanine", category: "Chromatic" },
  { name: "Pellucid", category: "Abstract" },
  { name: "Pentagonal", category: "Structural" },
  { name: "Pervenche", category: "Chromatic" },
  { name: "Petrichor", category: "Organic" },
  { name: "Phosphorescence", category: "Atmospheric" },
  { name: "Pyramidal", category: "Structural" },
  { name: "Refraction", category: "Atmospheric" },
  { name: "Resplendent", category: "Abstract" },
  { name: "Rugose", category: "Organic" },
  { name: "Sinusoidal", category: "Structural" },
  { name: "Solitude", category: "Abstract" },
  { name: "Striated", category: "Organic" },
  { name: "Toroidal", category: "Structural" },
  { name: "Vesicular", category: "Organic" },
  { name: "Viridian", category: "Chromatic" },
  { name: "Xylographic", category: "Structural" }
];
